apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: event-greeter-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Thanks for using OKD"}'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: my-demo-channel
